name: cuida_pet_back_end
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

dependencies:
  args: ^2.4.0
  crypto: ^3.0.3
  dotenv: 3.0.0
  get_it: ^7.7.0
  injectable: ^2.4.2
  injectable_generator: ^2.6.1
  jaguar_jwt: ^3.0.0
  logger: ^2.3.0
  mysql1: ^0.20.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_router_generator: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.9
  http: ^1.1.0
  lints: ^2.1.0
  test: ^1.24.0
